const reduce = matchMedia('(prefers-reduced-motion: reduce)').matches;
const intro = document.querySelector('#intro');
document.querySelector('#enter')?.addEventListener('click',()=>{intro?.classList.add('gone');document.body.classList.remove('lock');document.querySelector('.hero .reveal')?.classList.add('show')});

const canvas=document.querySelector('#space'),ctx=canvas?.getContext('2d');let stars=[],w=0,h=0,mx=.5,my=.5;
function resize(){if(!canvas)return;const d=devicePixelRatio||1;w=innerWidth;h=innerHeight;canvas.width=w*d;canvas.height=h*d;canvas.style.width=w+'px';canvas.style.height=h+'px';ctx.setTransform(d,0,0,d,0,0);stars=Array.from({length:w<700?130:280},()=>({x:Math.random()*w,y:Math.random()*h,r:.15+Math.random()*1.15,z:Math.random(),p:Math.random()*6.28}))}resize();addEventListener('resize',resize);addEventListener('pointermove',e=>{mx=e.clientX/w-.5;my=e.clientY/h-.5});
function render(t){if(!ctx)return;ctx.clearRect(0,0,w,h);for(const s of stars){const depth=.35+s.z*1.8,tw=.5+Math.sin(t*.0012+s.p)*.25;ctx.globalAlpha=tw*(.35+s.z*.65);ctx.fillStyle=s.z>.9?'#fff3d2':'#d8d8ec';ctx.beginPath();ctx.arc(s.x+mx*18*depth,s.y+my*12*depth,s.r*(.7+s.z),0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;if(!reduce)requestAnimationFrame(render)}requestAnimationFrame(render);
const observer=new IntersectionObserver(entries=>entries.forEach(e=>e.isIntersecting&&e.target.classList.add('show')),{threshold:.18});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const stage=document.querySelector('#stage');stage?.addEventListener('click',()=>stage.classList.toggle('kiss'));
const yes=document.querySelector('#yes'),later=document.querySelector('#later'),answer=document.querySelector('#answer');yes?.addEventListener('click',()=>{answer.innerHTML='<h4>Then it\'s a date. ❤️</h4><p>Maybe this is where our next chapter begins.</p>';document.querySelector('#date')?.scrollIntoView({behavior:reduce?'auto':'smooth'})});later?.addEventListener('click',()=>answer.innerHTML='<p>No pressure. Take your time. I\'ll still be glad you read this.</p>');
document.querySelectorAll('.date').forEach(card=>card.addEventListener('click',()=>{document.querySelectorAll('.date').forEach(x=>x.classList.remove('active'));card.classList.add('active');const out=document.querySelector('#dateAnswer');if(out)out.innerHTML='<h4>It\'s a plan. ✨</h4><p>'+card.textContent.trim()+' sounds perfect.</p>'}));
